### ISSUE TITLE
Error in create VPNSecurityGroup

### ISSUE THREAD

**Issue by diogopms** [webdigi/AWS-VPN-Server-Setup#3]
Hi, When i am trying to use your template, cloudformation tries to create a security group gives me this error.

```
10:59:54 UTC+0100   ROLLBACK_IN_PROGRESS    AWS::CloudFormation::Stack  MyVPN   The following resource(s) failed to create: [VPNSecurityGroup]. . Rollback requested by user.
```

Do you know if this template support the logic of VPC, associated with the security groups? 

Is good to add in the documentation how can we add more that one user :)

I can do a pull request if you what after i resolve this problem.

Thanks

**Comment by webdigi** [comment]
Did you manage to sort this? Pull requests are welcome

**Comment by ShiplakeCS** [comment]
I too have had this same issue when attempting to roll out the template today. Any ideas on how to overcome it? Sorry, I'm new to AWS so am not sure about setting up security groups, etc.

See screenshot of event history below.

<img width="1009" alt="screen shot 2017-06-01 at 14 24 09" src="https://cloud.githubusercontent.com/assets/24352915/26679593/19950b7c-46d6-11e7-8ac6-c5eddccdcc0d.png">

**Comment by webdigi** [comment]
Thanks for the screenshot. Please see https://forums.aws.amazon.com/thread.jspa?threadID=97448 "In order to subscribe to AWS services you must have a valid credit card listed on the account. This is true even if you've received promotional credits for usage."

Please check and report back. 

@diogopms did you have a valid credit card too?

**Comment by ShiplakeCS** [comment]
@webdigi I did/do have a valid credit card on the account, however I think the issue was down to my creating a new AWS account only very shortly before attempting to create the VPN stack. I have since tried again (waiting 24 hours) and it worked. So, I can only assume it takes a certain amount of time for all services to become active for new accounts.

**Comment by webdigi** [comment]
@ShiplakeCS - Thanks for getting back. A few users have mentioned this previously and we were never able to understand the cause. We will also have the [blog](https://www.webdigi.co.uk/blog/2015/how-to-setup-your-own-private-secure-free-vpn-on-the-amazon-aws-cloud-in-10-minutes/) and github readme updated with this notice.
