### ISSUE TITLE
Connecting from Windows 10 BuiltIn VPN client?

### ISSUE THREAD

**Issue by stephenjcole** [webdigi/AWS-VPN-Server-Setup#38]
Thanks for a great solution. It's been rock-solid with my iOS and Mac OS X devices but I'm banging my head against the wall with my Win10 machine. I've tried turning of the Windows Firewall and moved to different WiFi networks but without success. Also did my best to figure out which ports to open in the firewall through rules but I may not have been using the right ones.

I'm running the Shrew VPN client and a commercial VPN service (Witopia) on the same machine and both connect successfully (to other servers). Suggestions welcomed!

Thanks,

Steve

**Comment by webdigi** [comment]
several users have connected with Windows. Are you trying PPTP?

**Comment by stephenjcole** [comment]
Sorry, I wasn't specific. I had been trying only L2TP because I understand PPTP has been compromised. I just tried PPTP and got a similar (but not the same) error I see trying to connect with L2TP. Here's what I see with PPTP. I'll send the L2TP error in a separate comment.
![capture](https://user-images.githubusercontent.com/9205943/29638270-b5636604-8824-11e7-9ea2-e967d8152f76.JPG)

**Comment by stephenjcole** [comment]
Here's the L2TP error. FWIW, I'm using the Ohio AWS region.

By the way, thanks for the help. This is not mission-critical but it would be great if we could figure out the answer. 

![capture](https://user-images.githubusercontent.com/9205943/29638410-35b4cc8a-8825-11e7-94b5-934c017042ac.JPG)

**Comment by webdigi** [comment]
Thanks for the screenshots. Can you please try a mobile network with mobile data? Several users had problems previously as their work / university wifi blocks VPN connections.

**Comment by Josephzg** [comment]
I've encountered this issue too and figure out a solution might be helpful:
This is possibly due to the device is behind a NAT and requires registration change on `AssumeUDPEncapsulationContextOnSendRule`.
Please refer to https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-809 for quick solution and https://support.microsoft.com/en-gb/help/926179/how-to-configure-an-l2tp-ipsec-server-behind-a-nat-t-device-in-windows for detailed information.
