### ISSUE TITLE
why don't have the option of using t2.nano ec2 instance type?

### ISSUE THREAD

**Issue by yww325** [webdigi/AWS-VPN-Server-Setup#69]
just curious,I think that will cut the price in half.

**Comment by webdigi** [comment]
Just because nano was not available when we first built the script. Also is nano in the free tier?

**Comment by yww325** [comment]
Well, now it’s there.
t2.medium is not free either. For those who already passed one year free trial like me. t2.nano is the cheapest option.
so suggesting to provide it.

**Comment by shadowsaw** [comment]
I vouch for the same update please. It would be really helpful if we could select nano as an option.

**Comment by shadowsaw** [comment]
Here is a template for installing the VPN on other instances besides t2.micro. All credit to the original creators of the code. I have simply edited the JSON file. Enjoy :)

**Setup Instructions:**
- Download the zip file attached and unzip in a folder of your choice. (don't try to open it)
-Navigate to CloudFormation in AWS Console
-Select "Create Stack" in the region of your choice.
-Select "Template is ready"
-Select "Upload a template file"
-Select the unzipped file to upload to AWS
-The rest of the process is the same. 
(basically, you are uploading the template from your local machine instead of retrieving it from an Amazon S3 URL)

[VPN on Nano and Micro.zip](https://github.com/webdigi/AWS-VPN-Server-Setup/files/3428757/VPN.on.Nano.and.Micro.zip)

**Comment by shadowsaw** [comment]
Here is a template for installing the VPN on other instances besides t2.micro. All credit to the original creators of the code. I have simply edited the JSON file. Enjoy :)

**Setup Instructions:**

- Download the zip file attached and unzip in a folder of your choice. (don't try to open it)
- Navigate to CloudFormation in AWS Console
- Select "Create Stack" in the region of your choice.
- Select "Template is ready"
- Select "Upload a template file"
- Select the unzipped file to upload to AWS
- The rest of the process is the same

(basically, you are uploading the template from your local machine instead of retrieving it from an Amazon S3 URL)

The zip file to download: [VPN on Nano and Micro.zip](https://github.com/webdigi/AWS-VPN-Server-Setup/files/3428757/VPN.on.Nano.and.Micro.zip)
